---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  #  annotations:
  #    certmanager.k8s.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)
  name: cert-controller-mutating-webhook
webhooks:
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwakNDQWJxZ0F3SUJBZ0lKQU5jWkt4cnpiRHQ5TUEwR0NTcUdTSWIzRFFFQkN3VUFNQlV4RXpBUkJnTlYKQkFNTUNtdDFZbVZ5Ym1WMFpYTXdJQmNOTWpBd01UQTRNRFF3TmpBMVdoZ1BNakV4T1RFeU1UVXdOREEyTURWYQpNQlV4RXpBUkJnTlZCQU1NQ210MVltVnlibVYwWlhNd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3CmdnRUtBb0lCQVFDOEFua21WWGVKdmJxMWJYU3BpSE5rOC9oMHpFbkMxTEJZWW1vYVNaWHZQMmN2UlM3MmQ3b08KeVA5RWJEUWgzaFNZWGZ5YkcxZUUvME1DS1dTcHE0eHFGb1JFaTNxdE9DZy9oOVIyTHQ3U1VEeFhPTVRpWVpSWgpVNmk5dWIwYXcyS1BQKytGay9qODJ4SzR2Q1cyUHZRMk1pTXRnU1JtNFFzZ2d5VXMvZy9CL1VWeTcwSVBlY2Q4ClRyRXFmaXhKWGhJak15ZUE5eHRiV3dGUDdPR1creU1pa3pFREhVa3YvZzlSMll3d2VneEVlRUxjdGtVbjFCV3QKbUk0aGpNKzNLZjRIbVh5ellYaDhDZHhkVStJWjAxc1RTNHJ5K3ovS2hhc01Cd1VXYXM2WUFtWkNuMGMxbnV6UQpJektJU21uL3A4R0FqRDFtbWVWRmk0aWd4OTROejNUekFnTUJBQUdqSXpBaE1BOEdBMVVkRXdFQi93UUZNQU1CCkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2luRnM3OWFESTdnZFUKWXNZTDhqNjNlYUwvbkVGdXcvWWNxYjYva1EwNG4zbVlYQ3hleGQ3cVV1NXV4cXFSQlV4RXRaa1RrS3VNTE4wQgpkZG9ZSkdtV09rbEEwVjl6Z25ONk5tMXBMUmdrRUJ2cXAwT0FOaWZrNzJsaUFubFg0YkhTUWFWSy9aTmdDZkVjCkYzclFJWk01SEI4Nnc0b1J5YmQ0MHhCOGI4SzF6SHJHTXo1QVhERFNHREx4bnBxSGJJS1pJQ1djV1p4cElkQk8KNWNCSFJMZVpDa2dyTTB6QVNWdWlaRElBclduRk9LRVVsVlNkL2pyb3NhOW1wNkxZMy9vVnFjM2Y0eXg4cTdlQwo3RjBQY0JaL1g4SEtqSkltM3NQK0RUT3RzRUhXOXFJR3pYd2JmMlFBeXRzeU9weTNBOWRobk1zWTdxTVYyb3dNCksvdmtyZGhRCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      url: https://10.72.42.5:9876/mutating-create-ingress
#      service:
#        name: cert-controller-server
#        namespace: test
#        path: /mutating-create-ingress
    failurePolicy: Fail
    name: mcertcontroller.kb.io
    rules:
      - apiGroups:
          - extensions
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - ingresses
