apiVersion: apps/v1
kind: Deployment
metadata:
  name: certs-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: certs-controller
  template:
    metadata:
      labels:
        name: certs-controller
    spec:
      serviceAccountName: certs-controller
      containers:
        - name: certs-controller
          image: registry.cn-shenzhen.aliyuncs.com/jaywoods/cert-controller:0.1.0
          command:
          - certs-controller
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              value: ""
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "certs-controller"
