// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/jaywoods/certs-controller/pkg/apis/app/v1alpha1.CertSecretSpec":   schema_pkg_apis_app_v1alpha1_CertSecretSpec(ref),
		"github.com/jaywoods/certs-controller/pkg/apis/app/v1alpha1.CertSecretStatus": schema_pkg_apis_app_v1alpha1_CertSecretStatus(ref),
	}
}

func schema_pkg_apis_app_v1alpha1_CertSecretSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CertSecretSpec defines the desired state of CertSecret",
				Properties: map[string]spec.Schema{
					"tls": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("github.com/jaywoods/certs-controller/pkg/apis/app/v1alpha1.TlsData"),
									},
								},
							},
						},
					},
					"scope": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"namespaces": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
					"cascade": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"boolean"},
							Format: "",
						},
					},
				},
				Required: []string{"namespaces", "cascade"},
			},
		},
		Dependencies: []string{
			"github.com/jaywoods/certs-controller/pkg/apis/app/v1alpha1.TlsData"},
	}
}

func schema_pkg_apis_app_v1alpha1_CertSecretStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CertSecretStatus defines the observed state of CertSecret",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
